eureka:
  client:
    register-with-eureka: false
server:
  port: 7730
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clients
          uri: http://localhost:7710
          predicates:
            - Path=/api/v1/clients/**
        - id: cinemas
          uri: http://localhost:7720
          predicates:
            - Path=/api/v1/cinemas/**


