version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: cinemas
      POSTGRES_USER: imad
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
